# generated by datamodel-codegen:
#   filename:  baseline.json
#   timestamp: 2026-05-23T06:20:57+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, ConfigDict


class Error(BaseModel):
    model_config = ConfigDict(extra="allow")
    documentation_url: str = Field(..., description='Documentation link')
    message: str = Field(..., description='Error details')


class ModelSet(BaseModel):
    model_config = ConfigDict(extra="allow")
    all_access: bool | None = None
    built_in: bool | None = None
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    id: str | None = Field(None, description='Unique Id')
    models: list[str] | None = None
    name: str | None = Field(None, description='Name of ModelSet')
    url: str | None = Field(None, description='Link to get this item')


class PermissionSet(BaseModel):
    model_config = ConfigDict(extra="allow")
    all_access: bool | None = None
    built_in: bool | None = None
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    id: str | None = Field(None, description='Unique Id')
    name: str | None = Field(None, description='Name of PermissionSet')
    permissions: list[str] | None = None
    url: str | None = Field(None, description='Link to get this item')


class Role(BaseModel):
    model_config = ConfigDict(extra="allow")
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    id: str | None = Field(None, description='Unique Id')
    model_set: ModelSet | None = Field(None, description='(Read only) Model set')
    model_set_id: str | None = Field(None, description='(Write-Only) Id of model set')
    name: str | None = Field(None, description='Name of Role')
    permission_set: PermissionSet | None = Field(
        None, description='(Read only) Permission set'
    )
    permission_set_id: str | None = Field(
        None, description='(Write-Only) Id of permission set'
    )
    url: str | None = Field(None, description='Link to get this item')
    users_url: str | None = Field(
        None, description='Link to get list of users with this role'
    )


class ValidationErrorDetail(BaseModel):
    model_config = ConfigDict(extra="allow")
    code: str | None = Field(None, description='Error code')
    documentation_url: str = Field(..., description='Documentation link')
    field: str | None = Field(None, description='Field with error')
    message: str | None = Field(None, description='Error info message')


class ValidationError(BaseModel):
    model_config = ConfigDict(extra="allow")
    documentation_url: str = Field(..., description='Documentation link')
    errors: list[ValidationErrorDetail] | None = Field(
        None, description='Error detail array'
    )
    message: str = Field(..., description='Error details')
