# generated by datamodel-codegen:
#   filename:  baseline.json
#   timestamp: 2026-05-22T11:02:08+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, ConfigDict


class Error(BaseModel):
    model_config = ConfigDict(extra="allow")
    documentation_url: str = Field(..., description='Documentation link')
    message: str = Field(..., description='Error details')


class LookmlFieldLink(BaseModel):
    model_config = ConfigDict(extra="allow")
    icon_url: str | None = Field(
        None, description='A URL containing an image file to display with a link.'
    )
    label: str | None = Field(
        None, description='The name of the link as it would appear to users.'
    )
    url: str | None = Field(None, description='URL the link will go to.')


class LookmlModelExploreAccessFilter(BaseModel):
    model_config = ConfigDict(extra="allow")
    field: str | None = Field(None, description='Field to be filtered')
    user_attribute: str | None = Field(None, description='User attribute name')


class LookmlModelExploreAlias(BaseModel):
    model_config = ConfigDict(extra="allow")
    name: str | None = Field(None, description='Name')
    value: str | None = Field(None, description='Value')


class LookmlModelExploreAlwaysFilter(BaseModel):
    model_config = ConfigDict(extra="allow")
    name: str | None = Field(None, description='Name')
    value: str | None = Field(None, description='Value')


class LookmlModelExploreConditionallyFilter(BaseModel):
    model_config = ConfigDict(extra="allow")
    name: str | None = Field(None, description='Name')
    value: str | None = Field(None, description='Value')


class LookmlModelExploreError(BaseModel):
    model_config = ConfigDict(extra="allow")
    details: Any | None = Field(None, description='Details')
    error_pos: str | None = Field(None, description='Error source location')
    field_error: bool | None = Field(None, description='Is this a field error')
    message: str | None = Field(None, description='Error Message')


class LookmlModelExploreFieldEnumeration(BaseModel):
    model_config = ConfigDict(extra="allow")
    label: str | None = Field(None, description='Label')
    value: Any | None = Field(None, description='Value')


class LookmlModelExploreFieldMapLayer(BaseModel):
    model_config = ConfigDict(extra="allow")
    extents_json_url: str | None = Field(
        None,
        description='Specifies the URL to a JSON file that defines the geographic extents of each region available in the map layer. This data is used to automatically center the map on the available data for visualization purposes. The JSON file must be a JSON object where the keys are the mapping value of the feature (as specified by property_key) and the values are arrays of four numbers representing the west longitude, south latitude, east longitude, and north latitude extents of the region. The object must include a key for every possible value of property_key.',
    )
    feature_key: str | None = Field(
        None,
        description='Specifies the name of the TopoJSON object that the map layer references. If not specified, use the first object..',
    )
    format: str | None = Field(
        None,
        description='Specifies the data format of the region information. Valid values are: "topojson", "vector_tile_region".',
    )
    max_zoom_level: int | None = Field(
        None,
        description='The minimum zoom level that the map layer may be displayed at, for visualizations that support zooming.',
    )
    min_zoom_level: int | None = Field(
        None,
        description='The maximum zoom level that the map layer may be displayed at, for visualizations that support zooming.',
    )
    name: str | None = Field(
        None, description='Name of the map layer, as defined in LookML.'
    )
    projection: str | None = Field(
        None,
        description='The preferred geographic projection of the map layer when displayed in a visualization that supports multiple geographic projections.',
    )
    property_key: str | None = Field(
        None,
        description='Selects which property from the TopoJSON data to plot against. TopoJSON supports arbitrary metadata for each region. When null, the first matching property should be used.',
    )
    property_label_key: str | None = Field(
        None,
        description='Which property from the TopoJSON data to use to label the region. When null, property_key should be used.',
    )
    url: str | None = Field(None, description='URL to the map layer resource.')


class LookmlModelExploreFieldMeasureFilters(BaseModel):
    model_config = ConfigDict(extra="allow")
    condition: str | None = Field(None, description='Filter condition value')
    field: str | None = Field(None, description='Filter field name')


class LookmlModelExploreFieldPeriodOverPeriodParams(BaseModel):
    model_config = ConfigDict(extra="allow")
    based_on: str | None = Field(
        None,
        description='Specifies the measure that will be calculated over the different periods.',
    )
    based_on_time: str | None = Field(
        None,
        description='Specifies the time dimension that this measure will operate over.',
    )
    kind: str | None = Field(
        None,
        description='The type of calculation for the period_over_period measure. Valid values are: "previous", "difference", "relative_change".',
    )
    period: str | None = Field(
        None,
        description='Specifies the time frame for the comparison. Valid values are: "year", "fiscal_year", "quarter", "fiscal_quarter", "month", "week", "date".',
    )


class LookmlModelExploreFieldSqlCase(BaseModel):
    model_config = ConfigDict(extra="allow")
    condition: str | None = Field(None, description='SQL Case condition expression')
    value: str | None = Field(None, description='SQL Case label value')


class LookmlModelExploreFieldTimeInterval(BaseModel):
    model_config = ConfigDict(extra="allow")
    count: int | None = Field(
        None, description='The number of intervals this field represents a grouping of.'
    )
    name: str | None = Field(
        None,
        description='The type of time interval this field represents a grouping of. Valid values are: "day", "hour", "minute", "second", "millisecond", "microsecond", "week", "month", "quarter", "year".',
    )


class LookmlModelExploreJoins(BaseModel):
    model_config = ConfigDict(extra="allow")
    dependent_fields: list[str] | None = Field(
        None, description='Fields referenced by the join'
    )
    fields: list[str] | None = Field(
        None, description='Fields of the joined view to pull into this explore'
    )
    foreign_key: str | None = Field(
        None,
        description='Name of the dimension in this explore whose value is in the primary key of the joined view',
    )
    from_: str | None = Field(None, alias='from', description='Name of view to join')
    name: str | None = Field(
        None, description='Name of this join (and name of the view to join)'
    )
    outer_only: bool | None = Field(
        None, description='Specifies whether all queries must use an outer join'
    )
    relationship: str | None = Field(
        None, description='many_to_one, one_to_one, one_to_many, many_to_many'
    )
    required_joins: list[str] | None = Field(
        None, description='Names of joins that must always be included in SQL queries'
    )
    sql_foreign_key: str | None = Field(
        None, description='SQL expression that produces a foreign key'
    )
    sql_on: str | None = Field(
        None, description='SQL ON expression describing the join condition'
    )
    sql_table_name: str | None = Field(None, description='SQL table name to join')
    type: str | None = Field(
        None, description='The join type: left_outer, full_outer, inner, or cross'
    )
    view_label: str | None = Field(None, description='Label to display in UI selectors')


class LookmlModelExploreSet(BaseModel):
    model_config = ConfigDict(extra="allow")
    name: str | None = Field(None, description='Name')
    value: list[str] | None = Field(None, description='Value set')


class LookmlModelExploreSupportedMeasureType(BaseModel):
    model_config = ConfigDict(extra="allow")
    dimension_type: str | None = None
    measure_types: list[str] | None = None


class ValidationErrorDetail(BaseModel):
    model_config = ConfigDict(extra="allow")
    code: str | None = Field(None, description='Error code')
    documentation_url: str = Field(..., description='Documentation link')
    field: str | None = Field(None, description='Field with error')
    message: str | None = Field(None, description='Error info message')


class LookmlModelExploreField(BaseModel):
    model_config = ConfigDict(extra="allow")
    align: str | None = Field(
        None,
        description='The appropriate horizontal text alignment the values of this field should be displayed in. Valid values are: "left", "right".',
    )
    can_filter: bool | None = Field(
        None, description="Whether it's possible to filter on this field."
    )
    can_time_filter: bool | None = Field(
        None, description='Whether this field can be time filtered.'
    )
    category: str | None = Field(
        None,
        description='Field category Valid values are: "parameter", "filter", "measure", "dimension".',
    )
    default_filter_value: str | None = Field(
        None,
        description='The default value that this field uses when filtering. Null if there is no default value.',
    )
    description: str | None = Field(None, description='Description')
    dimension_group: str | None = Field(
        None,
        description='Dimension group if this field is part of a dimension group. If not, this will be null.',
    )
    drill_fields: list[str] | None = Field(
        None,
        description='Drill fields declared for this field in LookML or default drills for certain types.',
    )
    dynamic: bool | None = Field(
        None,
        description='Whether this field was specified in "dynamic_fields" and is not part of the model.',
    )
    enumerations: list[LookmlModelExploreFieldEnumeration] | None = Field(
        None,
        description='An array enumerating all the possible values that this field can contain. When null, there is no limit to the set of possible values this field can contain.',
    )
    error: str | None = Field(
        None,
        description='An error message indicating a problem with the definition of this field. If there are no errors, this will be null.',
    )
    field_group_label: str | None = Field(
        None,
        description='A label creating a grouping of fields. All fields with this label should be presented together when displayed in a UI.',
    )
    field_group_variant: str | None = Field(
        None,
        description='When presented in a field group via field_group_label, a shorter name of the field to be displayed in that context.',
    )
    fill_style: str | None = Field(
        None,
        description='The style of dimension fill that is possible for this field. Null if no dimension fill is possible. Valid values are: "enumeration", "range".',
    )
    filters: list[LookmlModelExploreFieldMeasureFilters] | None = Field(
        None,
        description='Array of filter conditions defined for the measure in LookML.',
    )
    fiscal_month_offset: int | None = Field(
        None,
        description='An offset (in months) from the calendar start month to the fiscal start month defined in the LookML model this field belongs to.',
    )
    has_allowed_values: bool | None = Field(
        None,
        description='Whether this field has a set of allowed_values specified in LookML.',
    )
    has_drills_metadata: bool | None = Field(
        None, description='Whether this field has links or drill fields defined.'
    )
    hidden: bool | None = Field(
        None, description='Whether this field should be hidden from the user interface.'
    )
    is_filter: bool | None = Field(None, description='Whether this field is a filter.')
    is_fiscal: bool | None = Field(
        None, description='Whether this field represents a fiscal time value.'
    )
    is_numeric: bool | None = Field(
        None,
        description='Whether this field is of a type that represents a numeric value.',
    )
    is_timeframe: bool | None = Field(
        None,
        description='Whether this field is of a type that represents a time value.',
    )
    label: str | None = Field(
        None, description='Fully-qualified human-readable label of the field.'
    )
    label_from_parameter: str | None = Field(
        None,
        description='The name of the parameter that will provide a parameterized label for this field, if available in the current context.',
    )
    label_short: str | None = Field(
        None,
        description='The human-readable label of the field, without the view label.',
    )
    links: list[LookmlFieldLink] | None = Field(
        None, description='Links associated with this field.'
    )
    lookml_link: str | None = Field(
        None,
        description='A URL linking to the definition of this field in the LookML IDE.',
    )
    map_layer: LookmlModelExploreFieldMapLayer | None = Field(
        None, description='If applicable, a map layer this field is associated with.'
    )
    measure: bool | None = Field(None, description='Whether this field is a measure.')
    name: str | None = Field(None, description='Fully-qualified name of the field.')
    original_view: str | None = Field(
        None,
        description='The name of the view this field is defined in. This will be different than "view" when the view has been joined via a different name using the "from" parameter.',
    )
    parameter: bool | None = Field(
        None, description='Whether this field is a parameter.'
    )
    period_over_period_params: LookmlModelExploreFieldPeriodOverPeriodParams | None = (
        Field(
            None,
            description='For measures of type period_over_period, this will return the individual metadata parameters.',
        )
    )
    permanent: bool | None = Field(
        None, description='Whether this field can be removed from a query.'
    )
    primary_key: bool | None = Field(
        None, description='Whether or not the field represents a primary key.'
    )
    project_name: str | None = Field(
        None, description='The name of the project this field is defined in.'
    )
    requires_refresh_on_sort: bool | None = Field(
        None,
        description="When true, it's not possible to re-sort this field's values without re-running the SQL query, due to database logic that affects the sort.",
    )
    scope: str | None = Field(
        None,
        description="The LookML scope this field belongs to. The scope is typically the field's view.",
    )
    sortable: bool | None = Field(None, description='Whether this field can be sorted.')
    source_file: str | None = Field(
        None, description='The path portion of source_file_path.'
    )
    source_file_path: str | None = Field(
        None,
        description='The fully-qualified path of the project file this field is defined in.',
    )
    sql: str | None = Field(
        None,
        description="SQL expression as defined in the LookML model. The SQL syntax shown here is a representation intended for auditability, and is not neccessarily an exact match for what will ultimately be run in the database. It may contain special LookML syntax or annotations that are not valid SQL. This will be null if the current user does not have the see_lookml permission for the field's model.",
    )
    sql_case: list[LookmlModelExploreFieldSqlCase] | None = Field(
        None,
        description="An array of conditions and values that make up a SQL Case expression, as defined in the LookML model. The SQL syntax shown here is a representation intended for auditability, and is not neccessarily an exact match for what will ultimately be run in the database. It may contain special LookML syntax or annotations that are not valid SQL. This will be null if the current user does not have the see_lookml permission for the field's model.",
    )
    strict_value_format: bool | None = Field(
        None,
        description='If yes, the field will not be localized with the user attribute number_format. Defaults to no',
    )
    suggest_dimension: str | None = Field(
        None, description='The name of the dimension to base suggest queries from.'
    )
    suggest_explore: str | None = Field(
        None, description='The name of the explore to base suggest queries from.'
    )
    suggestable: bool | None = Field(
        None, description='Whether or not suggestions are possible for this field.'
    )
    suggestions: list[str] | None = Field(
        None,
        description='If available, a list of suggestions for this field. For most fields, a suggest query is a more appropriate way to get an up-to-date list of suggestions. Or use enumerations to list all the possible values.',
    )
    tags: list[str] | None = Field(
        None,
        description='An array of arbitrary string tags provided in the model for this field.',
    )
    time_interval: LookmlModelExploreFieldTimeInterval | None = Field(
        None,
        description='Details on the time interval this field represents, if it is_timeframe.',
    )
    times_used: int | None = Field(
        None, description='The number of times this field has been used in queries'
    )
    type: str | None = Field(None, description='The LookML type of the field.')
    user_attribute_filter_types: list[str] | None = Field(
        None,
        description='An array of user attribute types that are allowed to be used in filters on this field. Valid values are: "advanced_filter_string", "advanced_filter_number", "advanced_filter_datetime", "string", "number", "datetime", "relative_url", "yesno", "zipcode".',
    )
    value_format: str | None = Field(
        None,
        description='If specified, the LookML value format string for formatting values of this field.',
    )
    view: str | None = Field(
        None, description='The name of the view this field belongs to.'
    )
    view_label: str | None = Field(
        None, description='The human-readable label of the view the field belongs to.'
    )
    week_start_day: str | None = Field(
        None,
        description='The name of the starting day of the week. Valid values are: "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday".',
    )


class LookmlModelExploreFieldset(BaseModel):
    model_config = ConfigDict(extra="allow")
    dimensions: list[LookmlModelExploreField] | None = Field(
        None, description='Array of dimensions'
    )
    filters: list[LookmlModelExploreField] | None = Field(
        None, description='Array of filters'
    )
    measures: list[LookmlModelExploreField] | None = Field(
        None, description='Array of measures'
    )
    parameters: list[LookmlModelExploreField] | None = Field(
        None, description='Array of parameters'
    )


class ValidationError(BaseModel):
    model_config = ConfigDict(extra="allow")
    documentation_url: str = Field(..., description='Documentation link')
    errors: list[ValidationErrorDetail] | None = Field(
        None, description='Error detail array'
    )
    message: str = Field(..., description='Error details')


class LookmlModelExplore(BaseModel):
    model_config = ConfigDict(extra="allow")
    access_filter_fields: list[str] | None = Field(
        None, description='(DEPRECATED) Array of access filter field names'
    )
    access_filters: list[LookmlModelExploreAccessFilter] | None = Field(
        None, description='Access filters'
    )
    aliases: list[LookmlModelExploreAlias] | None = Field(None, description='Aliases')
    always_filter: list[LookmlModelExploreAlwaysFilter] | None = Field(
        None, description='Always filter'
    )
    always_join: list[str] | None = Field(
        None,
        description='An array of joins that will always be included in the SQL for this explore, even if the user has not selected a field from the joined view.',
    )
    can_develop: bool | None = Field(None, description='Can Develop LookML')
    can_explain: bool | None = Field(None, description='Can Explain')
    can_pivot_in_db: bool | None = Field(None, description='Can pivot in the DB')
    can_save: bool | None = Field(None, description='Can Save')
    can_see_lookml: bool | None = Field(None, description='Can See LookML')
    can_subtotal: bool | None = Field(None, description='Can use subtotals')
    can_total: bool | None = Field(None, description='Can Total')
    conditionally_filter: list[LookmlModelExploreConditionallyFilter] | None = Field(
        None, description='Conditionally filter'
    )
    connection_name: str | None = Field(None, description='Connection name')
    description: str | None = Field(None, description='Description')
    errors: list[LookmlModelExploreError] | None = Field(None, description='Errors')
    fields: LookmlModelExploreFieldset | None = Field(None, description='Fields')
    files: list[str] | None = Field(None, description='List of model source files')
    group_label: str | None = Field(
        None, description='Label used to group explores in the navigation menus'
    )
    has_timezone_support: bool | None = Field(None, description='Has timezone support')
    hidden: bool | None = Field(None, description='Is hidden')
    id: str | None = Field(
        None, description='Fully qualified explore name (model name plus explore name)'
    )
    index_fields: list[str] | None = Field(None, description='Array of index fields')
    joins: list[LookmlModelExploreJoins] | None = Field(
        None, description='Views joined into this explore'
    )
    label: str | None = Field(None, description='Label')
    lookml_link: str | None = Field(
        None,
        description='A URL linking to the definition of this explore in the LookML IDE.',
    )
    model_name: str | None = Field(None, description='Name of model')
    name: str | None = Field(None, description='Explore name')
    null_sort_treatment: str | None = Field(
        None,
        description='How nulls are sorted, possible values are "low", "high", "first" and "last"',
    )
    project_name: str | None = Field(None, description='Name of project')
    scopes: list[str] | None = Field(None, description='Scopes')
    sets: list[LookmlModelExploreSet] | None = Field(None, description='Sets')
    source_file: str | None = Field(None, description='Primary source_file file')
    sql_table_name: str | None = Field(
        None,
        description='A sql_table_name expression that defines what sql table the view/explore maps onto. Example: "prod_orders2 AS orders" in a view named orders.',
    )
    supported_measure_types: list[LookmlModelExploreSupportedMeasureType] | None = (
        Field(
            None,
            description="An array of items describing which custom measure types are supported for creating a custom measure 'based_on' each possible dimension type.",
        )
    )
    supports_cost_estimate: bool | None = Field(
        None, description='Cost estimates supported'
    )
    tags: list[str] | None = Field(
        None,
        description='An array of arbitrary string tags provided in the model for this explore.',
    )
    title: str | None = Field(None, description='Explore title')
    view_name: str | None = Field(None, description='Name of view')
