"""Generated pydantic types + OpenAPI baseline for the explore_field entity.

Files:
    types.py      -- generated by scripts/regen_schema.py (datamodel-code-generator);
                     21 reachable schemas from LookmlModelExplore seeds, extra="allow"
                     on every class so undocumented API fields don't trip validation.
    baseline.json -- OpenAPI 3.0 subset (rewritten from Looker's Swagger 2.0 spec).
                     Bundled fallback; the live spec from `looker-extractor refresh-schema`
                     supersedes via the loader resolution chain.
"""
