# generated by datamodel-codegen:
#   filename:  baseline.json
#   timestamp: 2026-05-23T10:48:38+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, ConfigDict


class CredentialsApi3(BaseModel):
    model_config = ConfigDict(extra="allow")
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    client_id: str | None = Field(None, description='API key client_id')
    created_at: str | None = Field(
        None, description='Timestamp for the creation of this credential'
    )
    id: str | None = Field(None, description='Unique Id')
    is_disabled: bool | None = Field(
        None, description='Has this credential been disabled?'
    )
    type: str | None = Field(
        None, description='Short name for the type of this kind of credential'
    )
    url: str | None = Field(None, description='Link to get this item')


class CredentialsEmail(BaseModel):
    model_config = ConfigDict(extra="allow")
    account_setup_url: str | None = Field(
        None,
        description='Url with one-time use secret token that the user can use to setup account',
    )
    account_setup_url_expired: bool | None = Field(
        None, description='Is account_setup_url expired or not present?'
    )
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    created_at: str | None = Field(
        None, description='Timestamp for the creation of this credential'
    )
    email: str | None = Field(None, description='EMail address used for user login')
    forced_password_reset_at_next_login: bool | None = Field(
        None,
        description='Force the user to change their password upon their next login',
    )
    is_disabled: bool | None = Field(
        None, description='Has this credential been disabled?'
    )
    logged_in_at: str | None = Field(
        None, description='Timestamp for most recent login using credential'
    )
    password_reset_url: str | None = Field(
        None,
        description='Url with one-time use secret token that the user can use to reset password',
    )
    password_reset_url_expired: bool | None = Field(
        None, description='Is password_reset_url expired or not present?'
    )
    type: str | None = Field(
        None, description='Short name for the type of this kind of credential'
    )
    url: str | None = Field(None, description='Link to get this item')
    user_id: str | None = Field(None, description='Unique Id of the user')
    user_url: str | None = Field(None, description='Link to get this user')


class CredentialsEmailSearch(BaseModel):
    model_config = ConfigDict(extra="allow")
    account_setup_url: str | None = Field(
        None,
        description='Url with one-time use secret token that the user can use to setup account',
    )
    account_setup_url_expired: bool | None = Field(
        None, description='Is account_setup_url expired or not present?'
    )
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    created_at: str | None = Field(
        None, description='Timestamp for the creation of this credential'
    )
    email: str | None = Field(None, description='EMail address used for user login')
    forced_password_reset_at_next_login: bool | None = Field(
        None,
        description='Force the user to change their password upon their next login',
    )
    is_disabled: bool | None = Field(
        None, description='Has this credential been disabled?'
    )
    logged_in_at: str | None = Field(
        None, description='Timestamp for most recent login using credential'
    )
    password_reset_url: str | None = Field(
        None,
        description='Url with one-time use secret token that the user can use to reset password',
    )
    password_reset_url_expired: bool | None = Field(
        None, description='Is password_reset_url expired or not present?'
    )
    type: str | None = Field(
        None, description='Short name for the type of this kind of credential'
    )
    url: str | None = Field(None, description='Link to get this item')
    user_id: str | None = Field(None, description='Unique Id of the user')
    user_url: str | None = Field(None, description='Link to get this user')


class CredentialsEmbed(BaseModel):
    model_config = ConfigDict(extra="allow")
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    created_at: str | None = Field(
        None, description='Timestamp for the creation of this credential'
    )
    external_group_id: str | None = Field(
        None,
        description="Embedder's id for a group to which this user was added during the most recent login",
    )
    external_user_id: str | None = Field(
        None, description="Embedder's unique id for the user"
    )
    id: str | None = Field(None, description='Unique Id')
    is_disabled: bool | None = Field(
        None, description='Has this credential been disabled?'
    )
    logged_in_at: str | None = Field(
        None, description='Timestamp for most recent login using credential'
    )
    type: str | None = Field(
        None, description='Short name for the type of this kind of credential'
    )
    url: str | None = Field(None, description='Link to get this item')


class CredentialsGoogle(BaseModel):
    model_config = ConfigDict(extra="allow")
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    created_at: str | None = Field(
        None, description='Timestamp for the creation of this credential'
    )
    domain: str | None = Field(None, description='Google domain')
    email: str | None = Field(None, description='EMail address')
    google_user_id: str | None = Field(
        None, description="Google's Unique ID for this user"
    )
    is_disabled: bool | None = Field(
        None, description='Has this credential been disabled?'
    )
    logged_in_at: str | None = Field(
        None, description='Timestamp for most recent login using credential'
    )
    type: str | None = Field(
        None, description='Short name for the type of this kind of credential'
    )
    url: str | None = Field(None, description='Link to get this item')


class CredentialsLDAP(BaseModel):
    model_config = ConfigDict(extra="allow")
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    created_at: str | None = Field(
        None, description='Timestamp for the creation of this credential'
    )
    email: str | None = Field(None, description='EMail address')
    is_disabled: bool | None = Field(
        None, description='Has this credential been disabled?'
    )
    ldap_dn: str | None = Field(
        None, description='LDAP Distinguished name for this user (as-of the last login)'
    )
    ldap_id: str | None = Field(None, description='LDAP Unique ID for this user')
    logged_in_at: str | None = Field(
        None, description='Timestamp for most recent login using credential'
    )
    type: str | None = Field(
        None, description='Short name for the type of this kind of credential'
    )
    url: str | None = Field(None, description='Link to get this item')


class CredentialsLookerOpenid(BaseModel):
    model_config = ConfigDict(extra="allow")
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    created_at: str | None = Field(
        None, description='Timestamp for the creation of this credential'
    )
    email: str | None = Field(None, description='EMail address used for user login')
    is_disabled: bool | None = Field(
        None, description='Has this credential been disabled?'
    )
    logged_in_at: str | None = Field(
        None, description='Timestamp for most recent login using credential'
    )
    logged_in_ip: str | None = Field(
        None, description='IP address of client for most recent login using credential'
    )
    type: str | None = Field(
        None, description='Short name for the type of this kind of credential'
    )
    url: str | None = Field(None, description='Link to get this item')
    user_url: str | None = Field(None, description='Link to get this user')


class CredentialsOIDC(BaseModel):
    model_config = ConfigDict(extra="allow")
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    created_at: str | None = Field(
        None, description='Timestamp for the creation of this credential'
    )
    email: str | None = Field(None, description='EMail address')
    is_disabled: bool | None = Field(
        None, description='Has this credential been disabled?'
    )
    logged_in_at: str | None = Field(
        None, description='Timestamp for most recent login using credential'
    )
    oidc_user_id: str | None = Field(
        None, description="OIDC OP's Unique ID for this user"
    )
    type: str | None = Field(
        None, description='Short name for the type of this kind of credential'
    )
    url: str | None = Field(None, description='Link to get this item')


class CredentialsSaml(BaseModel):
    model_config = ConfigDict(extra="allow")
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    created_at: str | None = Field(
        None, description='Timestamp for the creation of this credential'
    )
    email: str | None = Field(None, description='EMail address')
    is_disabled: bool | None = Field(
        None, description='Has this credential been disabled?'
    )
    logged_in_at: str | None = Field(
        None, description='Timestamp for most recent login using credential'
    )
    saml_user_id: str | None = Field(
        None, description="Saml IdP's Unique ID for this user"
    )
    type: str | None = Field(
        None, description='Short name for the type of this kind of credential'
    )
    url: str | None = Field(None, description='Link to get this item')


class CredentialsTotp(BaseModel):
    model_config = ConfigDict(extra="allow")
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    created_at: str | None = Field(
        None, description='Timestamp for the creation of this credential'
    )
    is_disabled: bool | None = Field(
        None, description='Has this credential been disabled?'
    )
    type: str | None = Field(
        None, description='Short name for the type of this kind of credential'
    )
    url: str | None = Field(None, description='Link to get this item')
    verified: bool | None = Field(None, description='User has verified')


class Error(BaseModel):
    model_config = ConfigDict(extra="allow")
    documentation_url: str = Field(..., description='Documentation link')
    message: str = Field(..., description='Error details')


class Session(BaseModel):
    model_config = ConfigDict(extra="allow")
    browser: str | None = Field(None, description="User's browser type")
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    city: str | None = Field(
        None, description='City component of user location (derived from IP address)'
    )
    country: str | None = Field(
        None, description='Country component of user location (derived from IP address)'
    )
    created_at: str | None = Field(
        None, description='Time when this session was initiated'
    )
    credentials_type: str | None = Field(
        None, description='Type of credentials used for logging in this session'
    )
    expires_at: str | None = Field(
        None, description='Time when this session will expire'
    )
    extended_at: str | None = Field(
        None, description='Time when this session was last extended by the user'
    )
    extended_count: int | None = Field(
        None, description='Number of times this session was extended'
    )
    id: str | None = Field(None, description='Unique Id')
    ip_address: str | None = Field(
        None, description='IP address of user when this session was initiated'
    )
    operating_system: str | None = Field(None, description="User's Operating System")
    state: str | None = Field(
        None, description='State component of user location (derived from IP address)'
    )
    sudo_user_id: str | None = Field(
        None,
        description="Actual user in the case when this session represents one user sudo'ing as another",
    )
    url: str | None = Field(None, description='Link to get this item')


class User(BaseModel):
    model_config = ConfigDict(extra="allow")
    allow_direct_roles: bool | None = Field(
        None, description='User can be directly assigned a role.'
    )
    allow_normal_group_membership: bool | None = Field(
        None, description='User can be a direct member of a normal Looker group.'
    )
    allow_roles_from_normal_groups: bool | None = Field(
        None, description='User can inherit roles from a normal Looker group.'
    )
    avatar_url: str | None = Field(
        None, description='URL for the avatar image (may be generic)'
    )
    avatar_url_without_sizing: str | None = Field(
        None,
        description='URL for the avatar image (may be generic), does not specify size',
    )
    can: dict[str, bool] | None = Field(
        None,
        description='Operations the current user is able to perform on this object',
    )
    credentials_api3: list[CredentialsApi3] | None = Field(
        None, description='API credentials'
    )
    credentials_email: CredentialsEmail | None = Field(
        None, description='Email/Password login credentials'
    )
    credentials_embed: list[CredentialsEmbed] | None = Field(
        None, description='Embed credentials'
    )
    credentials_google: CredentialsGoogle | None = Field(
        None, description='Google auth credentials'
    )
    credentials_ldap: CredentialsLDAP | None = Field(
        None, description='LDAP credentials'
    )
    credentials_looker_openid: CredentialsLookerOpenid | None = Field(
        None, description='LookerOpenID credentials. Used for login by Looker Analysts'
    )
    credentials_oidc: CredentialsOIDC | None = Field(
        None, description='OpenID Connect auth credentials'
    )
    credentials_saml: CredentialsSaml | None = Field(
        None, description='Saml auth credentials'
    )
    credentials_totp: CredentialsTotp | None = Field(
        None, description='Two-factor credentials'
    )
    display_name: str | None = Field(
        None,
        description='Full name for display (available only if both first_name and last_name are set)',
    )
    email: str | None = Field(None, description='EMail address')
    embed_group_folder_id: str | None = Field(
        None,
        description="(Embed only) ID of user's group folder based on the external_group_id optionally specified during embed user login",
    )
    embed_group_space_id: str | None = Field(
        None,
        description="(DEPRECATED) (Embed only) ID of user's group space based on the external_group_id optionally specified during embed user login",
    )
    first_name: str | None = Field(None, description='First name')
    group_ids: list[str] | None = Field(
        None, description='Array of ids of the groups for this user'
    )
    home_folder_id: str | None = Field(
        None, description="ID string for user's home folder"
    )
    id: str | None = Field(None, description='Unique Id')
    is_disabled: bool | None = Field(None, description='Account has been disabled')
    is_iam_admin: bool | None = Field(
        None,
        description='User is an IAM Admin - only available in Looker (Google Cloud core)',
    )
    last_name: str | None = Field(None, description='Last name')
    locale: str | None = Field(
        None,
        description="User's preferred locale. User locale takes precedence over Looker's system-wide default locale. Locale determines language of display strings and date and numeric formatting in API responses. Locale string must be a 2 letter language code or a combination of language code and region code: 'en' or 'en-US', for example.",
    )
    looker_versions: list[str] | None = Field(
        None,
        description="Array of strings representing the Looker versions that this user has used (this only goes back as far as '3.54.0')",
    )
    models_dir_validated: bool | None = Field(
        None,
        description="User's dev workspace has been checked for presence of applicable production projects",
    )
    personal_folder_id: str | None = Field(
        None, description="ID of user's personal folder"
    )
    presumed_looker_employee: bool | None = Field(
        None, description='(DEPRECATED) User is identified as an employee of Looker'
    )
    role_ids: list[str] | None = Field(
        None, description='Array of ids of the roles for this user'
    )
    roles_externally_managed: bool | None = Field(
        None,
        description="User's roles are managed by an external directory like SAML or LDAP and can not be changed directly.",
    )
    sessions: list[Session] | None = Field(None, description='Active sessions')
    ui_state: dict[str, str] | None = Field(
        None,
        description='Per user dictionary of undocumented state information owned by the Looker UI.',
    )
    url: str | None = Field(None, description='Link to get this item')
    verified_looker_employee: bool | None = Field(
        None,
        description='User is identified as an employee of Looker who has been verified via Looker corporate authentication',
    )


class ValidationErrorDetail(BaseModel):
    model_config = ConfigDict(extra="allow")
    code: str | None = Field(None, description='Error code')
    documentation_url: str = Field(..., description='Documentation link')
    field: str | None = Field(None, description='Field with error')
    message: str | None = Field(None, description='Error info message')


class ValidationError(BaseModel):
    model_config = ConfigDict(extra="allow")
    documentation_url: str = Field(..., description='Documentation link')
    errors: list[ValidationErrorDetail] | None = Field(
        None, description='Error detail array'
    )
    message: str = Field(..., description='Error details')
